### ISSUE TITLE
[Bug] Anime list uses Romanised title when I use filter, otherwise it uses English, which I've selected. 

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [JICA98/DailyAL#12]
When I use the filter in anime list page it shows the name/title of the anime in Romanised format, instead of English, I've selected English in preference.

**Without Filter:**
![Screenshot_20240506-173752.jpg](https://github.com/JICA98/DailyAL/assets/79910450/403c95bb-28d1-4b98-9a57-456aab504773)

**With Filter:**
![Screenshot_20240506-173651.png](https://github.com/JICA98/DailyAL/assets/79910450/222b81e3-2485-4155-b3a1-3c6d32f67a87)

**Comment by JICA98** [comment]
Thanks for reporting this. Fix will be available in the next update.

**Comment by JICA98** [comment]
@0-BlackSpectrum-0 This is fixed in the latest update 2024.8.2+94. Check it out and please let me know if it still exists.

**Comment by 0-BlackSpectrum-0** [comment]
> @0-BlackSpectrum-0 This is fixed in the latest update 2024.8.2+94. Check it out and please let me know if it still exists.

Its working but there's a new issue, even though it shows title in English, it sorts the list on the basis of romanized name, so if I select sort by title, it doesn't start with A but from romanized A also same for filter titles starting with A also uses Romanized as a result it shows anime other than A
Example:
Place to Place which starts with P in English title is named Acchi Kocchi as romanized title, so it appears at top in sort by title and also appears in the filtered list which should only show anime that start with letter A!
