### ISSUE TITLE
watchlist  > list view ,   design improvement. More spacy

### ISSUE THREAD

**Issue by blackholeearth** [JICA98/DailyAL#14]
1st of All, Thanks for this great app.
 season  grid view , profile stats.. anime review section. İ was searching for sth like this.

------
**İssue**:
At Watchlist , list ui is too dense. Packed too tight.

New desing for the watchlist. less crowded.

For air date ;
* blue is easier to spot at first look. 
* Biggest value in the countdown is enough. (Considering the area which is small)
   * (For example: 5day in the photo)

![AddText_07-26-11 17 30](https://github.com/user-attachments/assets/2c1bb161-d06d-464d-838f-5f9efa6a9e65)

You dont have to delete old view. 
You can Add it as list comf-v2 or sth.

![new display -- list comfy v2](https://github.com/user-attachments/assets/23d4f5e1-5e1a-4f79-bb97-90590d22c132)

Best wishes... 
Hope to see this implemented....

**Comment by JICA98** [comment]
@blackholeearth I have added new display customization option in the latest release 2028.8.2+94.
This will allow users to create their own list views, I have only added it for anime as of now.
![image](https://github.com/user-attachments/assets/d5ac8ef9-ef7b-410e-8050-306405d7ab9d)

**Comment by blackholeearth** [comment]
OMG. thanks man. 

this is so complex. to make a editor for view!!!. wasnt expecting that.

i will edit it looking at my picture here. thanks so much again...

**Comment by blackholeearth** [comment]
thanks for trying.. but. there are  components that goes abnormal cordinations.

**steps::**
make a design. 
save it. 
open anime list . choose custom ui.
 **TV** and **"(5/12) progress"**  is located at different place than i set in the editor...

(also you can  see  "those 2 problematic ones" are jumping to another location when you rotate device..)
