### ISSUE TITLE
Gridview, Last item in watchlist,  is stretched to width of screen , 

### ISSUE THREAD

**Issue by blackholeearth** [JICA98/DailyAL#15]
Gridview, Last item in watchlist,  is stretched to width of screen , 

![Screenshot_20240806_232438](https://github.com/user-attachments/assets/896b6695-ed71-4f73-8745-c9b94afb0638)

**Comment by JICA98** [comment]
Hey @blackholeearth, this is fixed in the latest update 2024.8.2+94. Check it out and please let me know. Thanks :)

**Comment by blackholeearth** [comment]
fixed thanks.  V
