### ISSUE TITLE
Latest update has bugs

### ISSUE THREAD

**Issue by AnyoneMouse** [JICA98/DailyAL#3]
1. When I installed the latest update. The app that was previously installed didn't get updated. Instead a clone got installed. ![Screenshot_20240208-131822.jpg](https://github.com/JICA98/DailyAL/assets/85461823/a3a1a6b4-b4ae-444c-b351-18f1ff0c1f1f)

2. When I opened the app the font looks like this: ![Screenshot_20240208-132003.jpg](https://github.com/JICA98/DailyAL/assets/85461823/01d459bd-4e86-4db9-99db-485fa47985a8)

3. Was able to sign in but still nothing was normal.

**Comment by JICA98** [comment]
Hey @Tafim27 
1. New app uses a different applicationId to comply with Fdroid conventions (This is why you see two apps - one of them being the play store one). You will have to delete the older play store one.
2. I enabled flutter impeller rendering engine (which is newer engine to increase performance) but looks like it is causing issues. Please check the latest update, I'm using the older rendering engine for this build.
Thanks for reporting this!

**Comment by feelsavvy** [comment]
> 1. When I installed the latest update. The app that was previously installed didn't get updated. Instead a clone got installed. ![Screenshot_20240208-131822.jpg](https://private-user-images.githubusercontent.com/85461823/303243634-a3a1a6b4-b4ae-444c-b351-18f1ff0c1f1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzc2OTUsIm5iZiI6MTcwNzM3NzM5NSwicGF0aCI6Ii84NTQ2MTgyMy8zMDMyNDM2MzQtYTNhMWE2YjQtYjRhZS00NDRjLWIzNTEtMThmMWZmMGMxZjFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA3Mjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTY2NWQ5ZTZiMmQ3OTdmNjBlYTYxYTQzODJhOWQzMjA1YmJmNWY0ZDBjNDg1YzIxYmJiZWMwNTU5MTg1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ccur-wAGwlOZjGM-xWYih8skSSZXnuYMk4_DUvgH4BU)
> 2. When I opened the app the font looks like this: ![Screenshot_20240208-132003.jpg](https://private-user-images.githubusercontent.com/85461823/303244118-01d459bd-4e86-4db9-99db-485fa47985a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzc2OTUsIm5iZiI6MTcwNzM3NzM5NSwicGF0aCI6Ii84NTQ2MTgyMy8zMDMyNDQxMTgtMDFkNDU5YmQtNGU4Ni00ZGI5LTk5ZGItNDg1ZmE0Nzk4NWE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA3Mjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZmUwNzk4OWE4NTliYzk1ZTdjMWFlY2M2ZTk4ZTdjZDk1MjJkMGE1MDI1ZGZlYTYxZTcxNzgzNWI0YzNkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4nE5sp-ctZLYYQKMJhcPEbQInRnVqMWEjadxMcEERhA)
> 3. Was able to sign in but still nothing was normal.

1. You need to uninstall the previous app 

2. This was fixing

**Comment by AnyoneMouse** [comment]
> Hey @Tafim27 
> 1. New app uses a different applicationId to comply with Fdroid conventions (This is why you see two apps - one of them being the play store one). You will have to delete the older play store one.
> 2. I enabled flutter impeller rendering engine (which is newer engine to increase performance) but looks like it is causing issues. Please check the latest update, I'm using the older rendering engine for this build.
> Thanks for reporting this!

I deleted the play store one. And reinstalled the latest one. Still having same issue.
![Screenshot_20240208-133948.jpg](https://github.com/JICA98/DailyAL/assets/85461823/579fa5d5-3aa7-43ad-b97d-e7c05d314665)

Also I didn't really get what you meant in the first line of the second reply. I mean "flutter impeller rendering engine".
I guess that's because I don't really have any knowledge about programming and such.

I think I'll just revert back to the previous update for now.

**Comment by JICA98** [comment]
No worries, for you this issue is specific to this release: [88](https://github.com/JICA98/DailyAL/releases/tag/2024.2.1%2B88) right?
and it works for you in this build: [87](https://github.com/JICA98/DailyAL/releases/tag/2024.1.3%2B87).
I upgraded the version of flutter which I was using. This can also be causing this.
I will update here with a downgraded flutter version apk and check if it works for you or not.

**Comment by AnyoneMouse** [comment]
> No worries, for you this issue is specific to this release: [88](https://github.com/JICA98/DailyAL/releases/tag/2024.2.1%2B88) right?
> and it works for you in this build: [87](https://github.com/JICA98/DailyAL/releases/tag/2024.1.3%2B87).

Yup.

> I upgraded the version of flutter which I was using. This can also be causing this.
> I will update here with a downgraded flutter version apk and check if it works for you or not.

Okay.

**Comment by JICA98** [comment]
> Okay.

Can you please check if this apk works for you or not?
https://drive.google.com/file/d/1VJc4rftsl_bmb0dSwFYWiFYYldrQoAJ8/view?usp=sharing

**Comment by AnyoneMouse** [comment]
> > Okay.
> 
> Can you please check if this apk works for you or not?
> https://drive.google.com/file/d/1VJc4rftsl_bmb0dSwFYWiFYYldrQoAJ8/view?usp=sharing

I tried several times to install it (I have already uninstalled other versions beforehand) but unable to.

**Comment by JICA98** [comment]
> I tried several times to install it (I have already uninstalled other versions beforehand) but unable to.

Sorry, it looks like that apk had some issues. Can you try installing the fdroid one? https://f-droid.org/en/packages/io.github.jica98/

**Comment by AnyoneMouse** [comment]
> > I tried several times to install it (I have already uninstalled other versions beforehand) but unable to.
> 
> Sorry, it looks like that apk had some issues. Can you try installing the fdroid one? https://f-droid.org/en/packages/io.github.jica98/

Thanks. This one's working fine.

**Comment by JICA98** [comment]
Great!
