### ISSUE TITLE
App caps the display refresh rate to 60Hz

### ISSUE THREAD

**Issue by adarsh1001** [JICA98/DailyAL#5]
First up, really nice work on the app! It looks beautiful and I've not seen any other MAL client support News and Comments.

Coming to the issue:
In my display settings, I've forced the display refresh rate to 120Hz and all apps run on that refresh rate itself. However, DailyAL is running at 60Hz.

I've faced this issue with other Flutter FOSS apps as well, I think it needs some special handling as detailed here:

https://github.com/emavgl/oinkoin/issues/16#issuecomment-1823492267

Device: Nothing Phone (2)
Android: 14

**Comment by JICA98** [comment]
Thanks for reporting this and for sharing the similar issue. I will try making the changes by adding display_mode dependency.

**Comment by JICA98** [comment]
Hey @adarsh1001 I have added the mentioned library in the latest update. Check it out and please let me know if the issue still exists. Thanks :)

**Comment by adarsh1001** [comment]
Hi @JICA98, just checked. Working at 120Hz now! Thanks :)
