### ISSUE TITLE
Feature Suggestions for Start Up Page/List Page

### ISSUE THREAD

**Issue by gfactor** [JICA98/DailyAL#7]
My primary use case for this app is to update the shows I'm currently watching and mark which episodes I watched. While I can tell the app to start on the List page, I can't specify which tab of the List page to show. Would it be possible to select which tab of the List page the app should start on (such as selecting the Watching tab)?

Alternatively, would it be possible to allow the user to reorder or hide the tabs on the List page? That would let me set the Watching tab to be the first visible tab, making it easier for my use case.

**Comment by feelsavvy** [comment]
Thanks for suggesting this feature! It's already on our development list. Stay updated on our progress by joining our [Discord server](https://discord.gg/zvRZc9yF73).

**Comment by JICA98** [comment]
Hey @gfactor
This is implemented in the latest release. App will remember the position of the tab which you were on last time before closing the app.
Thanks for the suggestion.
