### ISSUE TITLE
Missing Anime Episode Countdown

### ISSUE THREAD

**Issue by Titoot** [JICA98/DailyAL#8]
Great app! This is the best alternative I have seen.

I noticed a bug and I'm glad to help improve it.

https://github.com/JICA98/DailyAL/blob/48c038463b64620cb7832b68825b4299ed3e645e/lib/api/dalapi.dart#L212
In this code segment, it retrieves timestamps from the API and filters by season (e.g., winter). However, the current running season is spring, and some animes are being filtered out even though they still have episodes to release.

For example, "Solo Leveling" is a winter season anime, but it's missing when using the spring season filter: [Winter Season API](https://dal-api.onrender.com/schedules?type=all&season=winter).
![image](https://github.com/JICA98/DailyAL/assets/82727556/7be5f9b4-ea74-46c4-9d3d-7080117235a3)
![image](https://github.com/JICA98/DailyAL/assets/82727556/395844f8-9f02-40d5-ac72-d857a7ae25d7)

Also, I'm curious why it's implemented this way and not like an API endpoint to retrieve specific anime by ID.

**Comment by feelsavvy** [comment]
Thanks for the compliment, choosing our app, and the bug report. Our developer is busy working on fixes, but we'll get back to you as soon as possible.
